/// Flutter icons MyFlutterApp
/// Copyright (C) 2022 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  MyFlutterApp
///      fonts:
///       - asset: fonts/MyFlutterApp.ttf
///
/// 
/// * Font Awesome 4, Copyright (C) 2016 by Dave Gandy
///         Author:    Dave Gandy
///         License:   SIL ()
///         Homepage:  http://fortawesome.github.com/Font-Awesome/
///
import 'package:flutter/widgets.dart';

class CustomIcons {
  CustomIcons._();

  static const _twitterFontFam = 'TwitterIcon';
  static const _instaFontFam = 'InstaIcon';
  static const _tiktokFontFam = 'TikTokIcon';
  static const _deviantFontFam = 'DeviantArtIcon';
  static const _websiteFontFam = 'LinkIcon';
  static const _pinterestFontFam = 'PinterestIcon';
  static const _artstationFontFam = 'ArtstationIcon';
  
  static const String? _kFontPkg = null;

  static const IconData twitter = IconData(0xf099, fontFamily: _twitterFontFam, fontPackage: _kFontPkg);

  static const IconData insta = IconData(0xe800, fontFamily: _instaFontFam, fontPackage: _kFontPkg);

  static const IconData tiktok = IconData(0xe800, fontFamily: _tiktokFontFam, fontPackage: _kFontPkg);

  static const IconData deviantArt = IconData(0xe800, fontFamily: _deviantFontFam, fontPackage: _kFontPkg);

  static const IconData website = IconData(0xe800, fontFamily: _websiteFontFam, fontPackage: _kFontPkg);

  static const IconData pinterest = IconData(0xe800, fontFamily: _pinterestFontFam, fontPackage: _kFontPkg);

  static const IconData artstation = IconData(0xe800, fontFamily: _artstationFontFam, fontPackage: _kFontPkg);
}
